package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	scraperServer "github.com/OrkWard/wormface/internal/server"
	_ "github.com/OrkWard/wormface/internal/server/docs" // docs is generated by Swag CLI
	"github.com/OrkWard/wormface/internal/server/handler"
	"github.com/OrkWard/wormface/pkg/youtube"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title		Scraper API
// @version		1.0
// @description	This is a scraper API server.
// @host		localhost:8080
// @BasePath	/
func main() {
	if err := run(); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}

func run() error {
	cfg, err := scraperServer.LoadConfig()
	if err != nil {
		return err
	}

	redisClient, err := scraperServer.NewRedisClient()
	if err != nil {
		return err
	}
	defer func() {
		if err := redisClient.Close(); err != nil {
			log.Printf("Error closing Redis client: %v", err)
		} else {
			log.Println("Redis client closed.")
		}
	}()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	ytClient, err := youtube.NewYouTubeClient(ctx)
	if err != nil {
		return err
	}

	router := http.NewServeMux()
	router.HandleFunc("/twitter/{userName}/posts", handler.MakeTwitterHandler(ctx, cfg.TwitterHeaders, redisClient))
	router.HandleFunc("/youtube/{channelName}/videos", handler.MakeYoutubeHandler(ytClient, redisClient))
	router.HandleFunc("/swagger/", httpSwagger.Handler())

	server := &http.Server{
		Addr:    ":8080",
		Handler: router,
	}

	go func() {
		log.Printf("Server starting on %s", server.Addr)
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed to listen: %v", err)
		}
	}()

	// Graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Server shutting down...")

	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer shutdownCancel()

	if err := server.Shutdown(shutdownCtx); err != nil {
		return fmt.Errorf("server shutdown failed: %w", err)
	}
	log.Println("Server gracefully stopped.")
	return nil
}
